name: Build Go Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # 3. Installer les dépendances
      - name: Install dependencies
        run: go mod tidy

      # 4. Compiler l'application
      - name: Build the application
        run: go build -o myapp

      # 5. Vérifier si le fichier binaire a été généré
      - name: Verify build
        run: ls -l myapp
